[build]
  command = "npm run build"  # Command to build your Next.js app
  publish = "out"             # Directory to publish (default for Next.js)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"  # Directory for serverless functions (if any)

[plugins]
  package = "@netlify/plugin-nextjs"  # Netlify plugin for Next.js
